// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"

	"wecom-go-app-demo/internal/svc"

	"github.com/tal-tech/go-zero/rest"
)

func RegisterHandlers(engine *rest.Server, serverCtx *svc.ServiceContext) {
	engine.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/zero/receive",
				Handler: zerogetHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/zero/receive",
				Handler: zeroreceiveHandler(serverCtx),
			},
		},
	)
}
